CI: add a stage that ensures the generated files are properly generated
This has 2 benefits:
- ensures the go scripts are still able to parse the input data
- ensures that the 2 generated files are in sync with their source

Signed-off-by: Benjamin Tissoires <benjamin.tissoires@redhat.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,6 @@
 stages:
   - build
+  - check
 
 build:
   image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/golang:alpine3.12
@@ -9,3 +10,41 @@ build:
   script:
     - cd scripts
     - make
+  artifacts:
+    paths:
+      - scripts/RHMAINTAINERS_parser
+      - scripts/yaml2CODEOWNERS
+      - scripts/yaml2RHMAINTAINERS
+
+check:
+  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/alpine:latest
+  stage: check
+  needs:
+    - build
+  before_script:
+    - apk add git
+  script:
+    # rebuild the current files
+    - ./scripts/yaml2CODEOWNERS info/owners.yaml > info/CODEOWNERS
+    - ./scripts/yaml2RHMAINTAINERS info/owners.yaml > info/RHMAINTAINERS
+
+    # clean up cache
+    - rm -f .failed
+
+    # check that the committed files matched
+    - git diff --exit-code || touch .failed
+    - |
+      if [[ -e .failed ]]
+      then
+        echo '-----------------------------------------------------------------'
+        echo ''
+        echo ' Looks like the files scripts/CODEOWNERS or scripts/RHMAINTAINERS'
+        echo ' have not been regenerated and checked in this commit.'
+        echo ''
+        echo ' Please run the following command before committing:'
+        echo '        ./scripts/yaml2CODEOWNERS info/owners.yaml > info/CODEOWNERS'
+        echo '        ./scripts/yaml2RHMAINTAINERS info/owners.yaml > info/RHMAINTAINERS'
+        echo ''
+        echo '-----------------------------------------------------------------'
+        exit 1
+      fi
