livepatch/klp-build: provide friendlier error messages
JIRA: https://redhat.atlassian.net/browse/RHEL-152194

commit b41d8b7d1752f2f85fc1a87f5e4f4dda45adad15
Author: Joe Lawrence <joe.lawrence@redhat.com>
Date:   Tue Mar 10 16:37:49 2026 -0400

    livepatch/klp-build: provide friendlier error messages

    Provide more context for common klp-build failure modes.  Clarify which
    user-provided patch is unsupported or failed to apply, and explicitly
    identify which kernel build (original or patched) failed.

    Acked-by: Song Liu <song@kernel.org>
    Signed-off-by: Joe Lawrence <joe.lawrence@redhat.com>
    Link: https://patch.msgid.link/20260310203751.1479229-11-joe.lawrence@redhat.com
    Signed-off-by: Josh Poimboeuf <jpoimboe@kernel.org>

Signed-off-by: Yannick Cote <ycote@redhat.com>

diff --git a/scripts/livepatch/klp-build b/scripts/livepatch/klp-build
--- a/scripts/livepatch/klp-build
+++ b/scripts/livepatch/klp-build
@@ -341,7 +341,7 @@ check_unsupported_patches() {
 		for file in "${files[@]}"; do
 			case "$file" in
 				lib/*|*.S)
-					die "unsupported patch to $file"
+					die "${patch}: unsupported patch to $file"
 					;;
 			esac
 		done
@@ -486,6 +486,7 @@ clean_kernel() {
 }
 
 build_kernel() {
+	local build="$1"
 	local log="$TMP_DIR/build.log"
 	local objtool_args=()
 	local cmd=()
@@ -523,7 +524,7 @@ build_kernel() {
 		"${cmd[@]}"							\
 			1> >(tee -a "$log")					\
 			2> >(tee -a "$log" | grep0 -v "modpost.*undefined!" >&2)
-	)
+	) || die "$build kernel build failed"
 }
 
 find_objects() {
@@ -798,7 +799,7 @@ fi
 if (( SHORT_CIRCUIT <= 1 )); then
 	status "Building original kernel"
 	clean_kernel
-	build_kernel
+	build_kernel "original"
 	status "Copying original object files"
 	copy_orig_objects
 fi
@@ -808,7 +809,7 @@ if (( SHORT_CIRCUIT <= 2 )); then
 	fix_patches
 	apply_patches
 	status "Building patched kernel"
-	build_kernel
+	build_kernel "patched"
 	revert_patches
 	status "Copying patched object files"
 	copy_patched_objects
