github actions: Github docs suggest pull_request_target
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request_target

Suggests using pull_request_target for forked repository workflows.

diff --git a/.github/workflows/process-pull-request.yml b/.github/workflows/process-pull-request.yml
--- a/.github/workflows/process-pull-request.yml
+++ b/.github/workflows/process-pull-request.yml
@@ -6,7 +6,7 @@
 name: Pull Request Checker
 
 on:
-  pull_request:
+  pull_request_target:
     branches:
       - '**'
       - '!mainline'    
@@ -39,7 +39,9 @@ jobs:
         /usr/bin/pip3 install gitPython
         python -c "import sys; import git; print(sys.version)"
         git fetch origin ${{ github.base_ref }}
-        git fetch origin ${{ github.head_ref }}
+        if ! git fetch origin ${{ github.head_ref }}; then
+          echo "Unable to checkout ${{ github.head_ref }}"
+        fi
         git remote add linux https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
         git fetch --shallow-since="3 years ago" linux
         echo "Will run process-git-request.rb with:"
