kernel.spec: fedora automotive build is not supported
JIRA: https://issues.redhat.com/browse/RHEL-88117
Upstream Status: https://gitlab.com/cki-project/kernel-ark.git

commit c8510c9a7732df1bb12d840e55ea743c112f19a2
Author: Scott Weaver <scweaver@redhat.com>
Date:   Wed Jun 11 20:07:32 2025 -0400

    kernel.spec: fedora automotive build is not supported

    Building automotive on fedora is not supported so we now catch this and
    exit the build.

    Suggested-by: Jarod Wilson <jarod@redhat.com>
    Signed-off-by: Scott Weaver <scweaver@redhat.com>

Signed-off-by: Scott Weaver <scweaver@redhat.com>

diff --git a/redhat/kernel.spec.template b/redhat/kernel.spec.template
--- a/redhat/kernel.spec.template
+++ b/redhat/kernel.spec.template
@@ -1865,6 +1865,13 @@ exit 1
 %endif
 %endif
 
+%if %{with_automotive}
+%if 0%{?fedora}
+%{log_msg "Cannot build automotive with a fedora baseline, must be rhel/centos/eln"}
+exit 1
+%endif
+%endif
+
 # more sanity checking; do it quietly
 if [ "%{patches}" != "%%{patches}" ] ; then
   for patch in %{patches} ; do
