redhat: Build kernel-rt as kernel variant
Bugzilla: https://bugzilla.redhat.com/2171995
Upstream Status: RHEL only

kernel-rt rpms have been traditionally built out of a separate source
tree as main package content. With the merge of PREEMPT_RT into stock
kernel sources, kernel-rt can now be built as a kernel variant.

Implement redhat machinery to build kernel-rt rpms as a kernel variant.

Signed-off-by: Juri Lelli <juri.lelli@redhat.com>

diff --git a/redhat/kernel.spec.template b/redhat/kernel.spec.template
--- a/redhat/kernel.spec.template
+++ b/redhat/kernel.spec.template
@@ -195,6 +195,8 @@ Summary: The Linux kernel
 %define with_zfcpdump  %{?_without_zfcpdump:  0} %{?!_without_zfcpdump:  1}
 # kernel-64k (aarch64 kernel with 64K page_size)
 %define with_arm64_64k %{?_without_arm64_64k: 0} %{?!_without_arm64_64k: 1}
+# kernel-rt (x86_64 and aarch64 only PREEMPT_RT enabled kernel)
+%define with_realtime  %{?_without_realtime:  0} %{?!_without_realtime:  1}
 # kernel-doc
 %define with_doc       %{?_without_doc:       0} %{?!_without_doc:       1}
 # kernel-headers
@@ -221,6 +223,8 @@ Summary: The Linux kernel
 %define with_paeonly   %{?_with_paeonly:      1} %{?!_with_paeonly:      0}
 # Only build the debug kernel (--with dbgonly):
 %define with_dbgonly   %{?_with_dbgonly:      1} %{?!_with_dbgonly:      0}
+# Only build the realtime kernel (--with rtonly):
+%define with_rtonly    %{?_with_rtonly:       1} %{?!_with_rtonly:       0}
 # Control whether we perform a compat. check against published ABI.
 %define with_kabichk   %{?_without_kabichk:   0} %{?!_without_kabichk:   1}
 # Temporarily disable kabi checks until RC.
@@ -358,10 +362,16 @@ Summary: The Linux kernel
 %define with_pae 0
 %endif
 
+# RT kernel is only built on x86_64
+%ifnarch x86_64
+%define with_realtime 0
+%endif
+
 # if requested, only build base kernel
 %if %{with_baseonly}
 %define with_pae 0
 %define with_debug 0
+%define with_realtime 0
 %define with_vdso_install 0
 %define with_perf 0
 %define with_tools 0
@@ -377,11 +387,29 @@ Summary: The Linux kernel
 %if %{with_paeonly}
 %define with_up 0
 %define with_debug 0
+%define with_realtime 0
 %endif
 
 # if requested, only build debug kernel
 %if %{with_dbgonly}
 %define with_up 0
+%define with_realtime 0
+%define with_vdso_install 0
+%define with_perf 0
+%define with_tools 0
+%define with_bpftool 0
+%define with_kernel_abi_stablelists 0
+%define with_selftests 0
+%define with_cross 0
+%define with_cross_headers 0
+%define with_ipaclones 0
+%endif
+
+# if requested, only build realtime kernel
+%if %{with_rtonly}
+%define with_up 0
+%define with_pae 0
+%define with_debug 0
 %define with_vdso_install 0
 %define with_perf 0
 %define with_tools 0
@@ -430,6 +458,7 @@ Summary: The Linux kernel
 # don't build noarch kernels or headers (duh)
 %ifarch noarch
 %define with_up 0
+%define with_realtime 0
 %define with_headers 0
 %define with_cross_headers 0
 %define with_tools 0
@@ -546,6 +575,7 @@ Summary: The Linux kernel
 %define with_pae 0
 %define with_zfcpdump 0
 %define with_arm64_64k 0
+%define with_realtime 0
 
 %define with_debuginfo 0
 %define with_perf 0
@@ -830,6 +860,9 @@ Source41: x509.genkey.centos
 # ARM64 64K page-size kernel config
 Source42: kernel-aarch64-64k-rhel.config
 Source43: kernel-aarch64-64k-debug-rhel.config
+
+Source44: kernel-x86_64-rt-rhel.config
+Source45: kernel-x86_64-rt-debug-rhel.config
 %endif
 
 %if 0%{?include_fedora}
@@ -865,6 +898,7 @@ Source82: update_scripts.sh
 
 Source84: mod-internal.list
 Source85: mod-partner.list
+Source86: mod-kvm.list
 
 Source100: rheldup3.x509
 Source101: rhelkpatch1.x509
@@ -1273,6 +1307,24 @@ AutoProv: yes\
 This package provides kernel modules for the %{?2:%{2} }kernel package for Red Hat internal usage.\
 %{nil}
 
+%if %{with_realtime}
+#
+# this macro creates a kernel-<subpackage>-kvm package
+# %%kernel_kvm_package <subpackage>
+#
+%define kernel_kvm_package() \
+%package %{?1:%{1}-}kvm\
+Summary: KVM modules for package kernel%{?1:-%{1}}\
+Group: System Environment/Kernel\
+Requires: kernel%{?1:-%{1}} = %{version}-%{release}\
+Provides: installonlypkg(kernel-module)\
+Provides: kernel%{?1:-%{1}}-kvm-%{_target_cpu} = %{version}-%{release}\
+AutoReq: no\
+%description -n kernel%{?1:-%{1}}-kvm\
+This package provides KVM modules for package kernel%{?1:-%{1}}.\
+%{nil}
+%endif
+
 #
 # This macro creates a kernel-<subpackage>-modules-extra package.
 #	%%kernel_modules_extra_package [-m] <subpackage> <pretty-name>
@@ -1352,6 +1404,9 @@ summary: kernel meta-package for the %{1} kernel\
 Requires: kernel-%{1}-core-uname-r = %{KVERREL}%{uname_suffix %{1}}\
 Requires: kernel-%{1}-modules-uname-r = %{KVERREL}%{uname_suffix %{1}}\
 Requires: kernel-%{1}-modules-core-uname-r = %{KVERREL}%{uname_suffix %{1}}\
+%if "%{1}" == "rt" || "%{1}" == "rt-debug"\
+Requires: realtime-setup\
+%endif\
 Provides: installonlypkg(kernel)\
 %description %{1}\
 The meta-package for the %{1} kernel\
@@ -1388,12 +1443,17 @@ Requires: kernel-%{?1:%{1}-}-modules-core-uname-r = %{KVERREL}%{uname_variant %{
 %{expand:%%kernel_debuginfo_package %{?1:%{1}}}\
 %endif\
 %if %{efiuki}\
+%if "%{1}" != "rt" && "%{1}" != "rt-debug"\
 %package %{?1:%{1}-}uki-virt\
 Summary: %{variant_summary} unified kernel image for virtual machines\
 Provides: installonlypkg(kernel)\
 Provides: kernel-%{?1:%{1}-}uname-r = %{KVERREL}%{uname_suffix %{?1:%{1}}}\
 Requires: kernel%{?1:-%{1}}-modules-core-uname-r = %{KVERREL}%{uname_suffix %{?1:%{1}}}\
 %endif\
+%endif\
+%if "%{1}" == "rt" || "%{1}" == "rt-debug"\
+%{expand:%%kernel_kvm_package %{?1:%{1}}} %{!?{-n}:%{1}}%{?{-n}:%{-n*}}}\
+%endif \
 %{nil}
 
 #
@@ -1455,6 +1515,24 @@ a 64K page size.
 The debug kernel package contains a variant of the ARM64 Linux kernel using
 a 64K page size.
 This variant of the kernel has numerous debugging options enabled.
+It should only be installed when trying to gather additional information
+on kernel bugs, as some of these options impact performance noticably.
+%endif
+
+%if %{with_realtime}
+%define variant_summary The Linux kernel compiled with PREEMPT_RT enabled
+%kernel_variant_package rt
+%description rt-core
+This package includes a version of the Linux kernel compiled with PREEMPT_RT
+(real-time preemption support).
+%endif
+
+%if %{with_debug} && %{with_realtime}
+%define variant_summary The Linux kernel compiled with PREEMPT_RT enabled
+%kernel_variant_package rt-debug
+%description rt-debug-core
+This package includes a version of the Linux kernel compiled with PREEMPT_RT
+(real-time preemption support) and has numerous debugging options enabled.
 It should only be installed when trying to gather additional information
 on kernel bugs, as some of these options impact performance noticably.
 %endif
@@ -2219,6 +2297,10 @@ BuildKernel() {
     # Identify modules in the kernel-modules-partner package
     %{SOURCE20} $RPM_BUILD_ROOT lib/modules/$KernelVer %{SOURCE85} partner
 %endif
+    if [ "$Variant" = "rt" ] || [ "$Variant" = "rt-debug" ]; then
+        # Identify modules in the kernel-rt-kvm package
+        %{SOURCE20} $RPM_BUILD_ROOT lib/modules/$KernelVer %{SOURCE86} kvm
+    fi
 
     #
     # Generate the kernel-core and kernel-modules files lists
@@ -2240,6 +2322,10 @@ BuildKernel() {
     # don't include anything going int kernel-modules-partner in the file lists
     xargs rm -rf < mod-partner.list
 %endif
+    if [ "$Variant" = "rt" ] || [ "$Variant" = "rt-debug" ]; then
+        # don't include anything going into kernel-rt-kvm in the file lists
+        xargs rm -rf < mod-kvm.list
+    fi
 
     if [ $DoModules -eq 1 ]; then
 	# Find all the module files and filter them out into the core and
@@ -2270,38 +2356,41 @@ BuildKernel() {
     fi
 
 %if %{efiuki}
-    popd
-
-    KernelUnifiedImageDir="$RPM_BUILD_ROOT/lib/modules/$KernelVer"
-    KernelUnifiedImage="$KernelUnifiedImageDir/$InstallName-virt.efi"
-
-    mkdir -p $KernelUnifiedImageDir
-
-    dracut --conf=%{SOURCE150} \
-           --confdir=$(mktemp -d) \
-           --verbose \
-           --kver "$KernelVer" \
-           --kmoddir "$RPM_BUILD_ROOT/lib/modules/$KernelVer/" \
-           --logfile=$(mktemp) \
-           --uefi \
-           --kernel-image $(realpath $KernelImage) \
-           --kernel-cmdline 'console=tty0 console=ttyS0' \
-	   $KernelUnifiedImage
+    if [ "$Variant" != "rt" ] && [ "$Variant" != "rt-debug" ]; then
+        popd
+    
+        KernelUnifiedImageDir="$RPM_BUILD_ROOT/lib/modules/$KernelVer"
+        KernelUnifiedImage="$KernelUnifiedImageDir/$InstallName-virt.efi"
+    
+        mkdir -p $KernelUnifiedImageDir
+    
+        dracut --conf=%{SOURCE150} \
+               --confdir=$(mktemp -d) \
+               --verbose \
+               --kver "$KernelVer" \
+               --kmoddir "$RPM_BUILD_ROOT/lib/modules/$KernelVer/" \
+               --logfile=$(mktemp) \
+               --uefi \
+               --kernel-image $(realpath $KernelImage) \
+               --kernel-cmdline 'console=tty0 console=ttyS0' \
+    	   $KernelUnifiedImage
 
 %if %{signkernel}
 
-    %pesign -s -i $KernelUnifiedImage -o $KernelUnifiedImage.signed -a %{secureboot_ca_0} -c %{secureboot_key_0} -n %{pesign_name_0}
-    if [ ! -s $KernelUnifiedImage.signed ]; then
-      echo "pesigning failed"
-      exit 1
-    fi
-    mv $KernelUnifiedImage.signed $KernelUnifiedImage
+        %pesign -s -i $KernelUnifiedImage -o $KernelUnifiedImage.signed -a %{secureboot_ca_0} -c %{secureboot_key_0} -n %{pesign_name_0}
+        if [ ! -s $KernelUnifiedImage.signed ]; then
+          echo "pesigning failed"
+          exit 1
+        fi
+        mv $KernelUnifiedImage.signed $KernelUnifiedImage
 
 # signkernel
 %endif
 
-    pushd $RPM_BUILD_ROOT
+        pushd $RPM_BUILD_ROOT
 
+    # Variant != rt && Variant != rt-debug
+    fi
 # efiuki
 %endif
 
@@ -2334,6 +2423,9 @@ BuildKernel() {
 %if 0%{!?fedora:1}
     sed -e 's/^lib*/\/lib/' %{?zipsed} $RPM_BUILD_ROOT/mod-partner.list >> ../kernel${Variant:+-${Variant}}-modules-partner.list
 %endif
+    if [ "$Variant" = "rt" ] || [ "$Variant" = "rt-debug" ]; then
+        sed -e 's/^lib*/\/lib/' %{?zipsed} $RPM_BUILD_ROOT/mod-kvm.list >> ../kernel${Variant:+-${Variant}}-kvm.list
+    fi
 
     # Cleanup
     rm -f $RPM_BUILD_ROOT/k-d.list
@@ -2344,6 +2436,9 @@ BuildKernel() {
 %if 0%{!?fedora:1}
     rm -f $RPM_BUILD_ROOT/mod-partner.list
 %endif
+    if [ "$Variant" = "rt" ] || [ "$Variant" = "rt-debug" ]; then
+        rm -f $RPM_BUILD_ROOT/mod-kvm.list
+    fi
 
 %if %{with_cross}
     make -C $RPM_BUILD_ROOT/lib/modules/$KernelVer/build M=scripts clean
@@ -2429,6 +2524,9 @@ BuildKernel %make_target %kernel_image %{_use_vdso} debug
 %if %{with_arm64_64k}
 BuildKernel %make_target %kernel_image %{_use_vdso} 64k-debug
 %endif
+%if %{with_realtime}
+BuildKernel %make_target %kernel_image %{_use_vdso} rt-debug
+%endif
 %endif
 
 %if %{with_zfcpdump}
@@ -2443,12 +2541,16 @@ BuildKernel %make_target %kernel_image %{_use_vdso} 64k
 BuildKernel %make_target %kernel_image %{use_vdso} lpae
 %endif
 
+%if %{with_realtime}
+BuildKernel %make_target %kernel_image %{use_vdso} rt
+%endif
+
 %if %{with_up}
 BuildKernel %make_target %kernel_image %{_use_vdso}
 %endif
 
 %ifnarch noarch i686
-%if !%{with_debug} && !%{with_zfcpdump} && !%{with_pae} && !%{with_up} && !%{with_arm64_64k}
+%if !%{with_debug} && !%{with_zfcpdump} && !%{with_pae} && !%{with_up} && !%{with_arm64_64k} && !%{with_realtime}
 # If only building the user space tools, then initialize the build environment
 # and some variables so that the various userspace tools can be built.
 InitBuildVars
@@ -2596,6 +2698,9 @@ find Documentation -type d | xargs chmod u+w
     if [ "%{with_pae}" -ne "0" ]; then \
        %{modsign_cmd} certs/signing_key.pem.sign+lpae certs/signing_key.x509.sign+lpae $RPM_BUILD_ROOT/lib/modules/%{KVERREL}+lpae/ \
     fi \
+    if [ "%{with_realtime}" -ne "0" ]; then \
+       %{modsign_cmd} certs/signing_key.pem.sign+rt certs/signing_key.x509.sign+rt $RPM_BUILD_ROOT/lib/modules/%{KVERREL}+rt/ \
+    fi \
     if [ "%{with_debug}" -ne "0" ]; then \
          %{modsign_cmd} certs/signing_key.pem.sign+debug certs/signing_key.x509.sign+debug $RPM_BUILD_ROOT/lib/modules/%{KVERREL}+debug/ \
     fi \
@@ -2604,6 +2709,9 @@ find Documentation -type d | xargs chmod u+w
     fi \
     if [ "%{with_arm64_64k}" -ne "0" ] && [ "%{with_debug}" -ne "0"]; then \
          %{modsign_cmd} certs/signing_key.pem.sign+64k-debug certs/signing_key.x509.sign+64k-debug $RPM_BUILD_ROOT/lib/modules/%{KVERREL}+64k-debug/ \
+    fi \
+    if [ "%{with_realtime}" -ne "0" ] && [ "%{with_debug}" -ne "0"]; then \
+         %{modsign_cmd} certs/signing_key.pem.sign+rt-debug certs/signing_key.x509.sign+rt-debug $RPM_BUILD_ROOT/lib/modules/%{KVERREL}+rt-debug/ \
     fi \
     if [ "%{with_up}" -ne "0" ]; then \
       %{modsign_cmd} certs/signing_key.pem.sign certs/signing_key.x509.sign $RPM_BUILD_ROOT/lib/modules/%{KVERREL}/ \
@@ -2987,6 +3095,21 @@ fi\
 /sbin/depmod -a %{KVERREL}%{?1:+%{1}}\
 %{nil}
 
+%if %{with_realtime}
+#
+# This macro defines a %%post script for a kernel*-kvm package.
+# It also defines a %%postun script that does the same thing.
+#       %%kernel_kvm_post [<subpackage>]
+#
+%define kernel_kvm_post() \
+%{expand:%%post %{?1:%{1}-}kvm}\
+/sbin/depmod -a %{KVERREL}%{?1:+%{1}}\
+%{nil}\
+%{expand:%%postun %{?1:%{1}-}kvm}\
+/sbin/depmod -a %{KVERREL}%{?1:+%{1}}\
+%{nil}
+%endif
+
 #
 # This macro defines a %%post script for a kernel*-modules-partner package.
 # It also defines a %%postun script that does the same thing.
@@ -3082,6 +3205,14 @@ if [ `uname -i` == "x86_64" -o `uname -i` == "i386" ] &&\
 fi}\
 mkdir -p %{_localstatedir}/lib/rpm-state/%{name}\
 touch %{_localstatedir}/lib/rpm-state/%{name}/installing_core_%{KVERREL}%{?-v:+%{-v*}}\
+%if "%{1}" == "rt" || "%{1}" == "rt-debug"\
+%{expand:%%post %{?1:%{1}-}kvm}\
+/sbin/depmod -a %{KVERREL}%{?1:+%{1}}\
+%{nil}\
+%{expand:%%postun %{?1:%{1}-}kvm}\
+/sbin/depmod -a %{KVERREL}%{?1:+%{1}}\
+%{nil}\
+%endif\
 %{nil}
 
 #
@@ -3136,6 +3267,16 @@ fi\
 %if %{with_debug} && %{with_arm64_64k}
 %kernel_variant_preun 64k-debug
 %kernel_variant_post -v 64k-debug
+%endif
+
+%if %{with_realtime}
+%kernel_variant_preun rt
+%kernel_variant_post -v rt
+%endif
+
+%if %{with_debug} && %{with_realtime}
+%kernel_variant_preun rt-debug
+%kernel_variant_post -v rt-debug
 %endif
 
 %if %{with_debug}
@@ -3374,15 +3515,20 @@ fi
 %if 0%{!?fedora:1}\
 %{expand:%%files -f kernel-%{?3:%{3}-}modules-partner.list %{?3:%{3}-}modules-partner}\
 %endif\
+%if "%{3}" == "rt" || "%{3}" == "rt-debug"\
+%{expand:%%files -f kernel-%{?3:%{3}-}kvm.list %{?3:%{3}-}kvm}\
+%endif\
 %if %{with_debuginfo}\
 %ifnarch noarch\
 %{expand:%%files -f debuginfo%{?3}.list %{?3:%{3}-}debuginfo}\
 %endif\
 %endif\
 %if %{efiuki}\
+%if "%{3}" != "rt" && "%{3}" != "rt-debug"\
 %{expand:%%files %{?3:%{3}-}uki-virt}\
 /lib/modules/%{KVERREL}%{?3:+%{3}}/%{?-k:%{-k*}}%{!?-k:vmlinuz}-virt.efi\
 %ghost /%{image_install_path}/efi/EFI/Linux/%{?-k:%{-k*}}%{!?-k:vmlinuz}-%{KVERREL}%{?3:+%{3}}-virt.efi\
+%endif\
 %endif\
 %if %{?3:1} %{!?3:0}\
 %{expand:%%files %{3}}\
@@ -3394,6 +3540,10 @@ fi
 %kernel_variant_files %{_use_vdso} %{with_debug} debug
 %if %{with_arm64_64k}
 %kernel_variant_files %{_use_vdso} %{with_debug} 64k-debug
+%endif
+%kernel_variant_files %{_use_vdso} %{with_realtime} rt
+%if %{with_realtime}
+%kernel_variant_files %{_use_vdso} %{with_debug} rt-debug
 %endif
 %if %{with_debug_meta}
 %files debug
